import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import Footer from "@/components/Footer";
import ShippingInfo from "@/components/ShippingInfo";

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${josefinSans.variable} antialiased`}>
      <ClerkProvider>
        <Header />
        <main>{children}</main>
        <SanityLive />
        <ShippingInfo />
        <Footer />
      </ClerkProvider>
    </div>
  );
}
